"""empty message

Revision ID: 66ce7aad4cbe
Revises: 81705343fa4f
Create Date: 2026-03-02 12:30:04.967423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ce7aad4cbe'
down_revision = '81705343fa4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_state',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['azmoon.id'], name='fk_real_exam_id'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='fk_real_user_state_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_state'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    # ### end Alembic commands ###
