"""empty message

Revision ID: 79dbf5a23843
Revises: c6e953dde679
Create Date: 2026-02-02 17:32:48.767543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dbf5a23843'
down_revision = 'c6e953dde679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('azmoon', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_azmoon_name'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('azmoon', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_azmoon_name'), ['name'])

    # ### end Alembic commands ###
