"""empty message

Revision ID: c6e953dde679
Revises: 
Create Date: 2026-01-30 17:01:40.027440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e953dde679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher')),
    sa.UniqueConstraint('username', name=op.f('uq_teacher_username'))
    )
    op.create_table('azmoon',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_azmoon_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_azmoon')),
    sa.UniqueConstraint('name', name=op.f('uq_azmoon_name'))
    )
    op.create_table('real_question',
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('azmoon_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['azmoon_id'], ['azmoon.id'], name='fk_real_question_azmoon_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_real_question'))
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('azmoon_id', sa.Integer(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['azmoon_id'], ['azmoon.id'], name=op.f('fk_user_azmoon_id_azmoon')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_user_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('real_option',
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['real_question.id'], name='fk_real_option_question_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_real_option'))
    )
    op.create_table('result',
    sa.Column('for_student', sa.Integer(), nullable=False),
    sa.Column('for_azmoon_name', sa.String(length=50), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['for_azmoon_name'], ['azmoon.name'], name=op.f('fk_result_for_azmoon_name_azmoon')),
    sa.ForeignKeyConstraint(['for_student'], ['user.id'], name=op.f('fk_result_for_student_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result'))
    )
    op.create_table('answer',
    sa.Column('for_student', sa.Integer(), nullable=False),
    sa.Column('for_question', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer'], ['real_option.id'], name=op.f('fk_answer_answer_real_option')),
    sa.ForeignKeyConstraint(['for_question'], ['real_question.id'], name=op.f('fk_answer_for_question_real_question')),
    sa.ForeignKeyConstraint(['for_student'], ['user.id'], name=op.f('fk_answer_for_student_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('result')
    op.drop_table('real_option')
    op.drop_table('user')
    op.drop_table('real_question')
    op.drop_table('azmoon')
    op.drop_table('teacher')
    # ### end Alembic commands ###
